# Generated by Django 3.1.5 on 2021-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_customuser_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
